### ISSUE TITLE
Tema Mağazası Çalışmıyor

### ISSUE THREAD

**Issue by seyitacar** [ingbrzy/MA-XML-7.0-TURKISH#11]
MIUI V7'de Temalar uygulamasına girildiğinde "Liste Yüklenemedi" hatası alınıyor, temalarda arama yapınca sonuçları gösteriyor arama yapmadan tema görüntüleyemiyoruz ayrıca dili ingilizceye çevirince bu sorun ortadan kalkıyor 

Cihaz: Redmi Note 2

**Comment by cmadencan** [comment]
bahsettiğin sorun tr çeviri ile alaklı değil. birkaç dil daricinde diğer
dillerde bahsettiğin durum yaşanıyor. ingbrzy e yazmıştım ama bir
değişiklik olmadı..

1 Ekim 2015 20:31 tarihinde seyitacar23 <notifications@github.com> yazdı:

**Comment by xtrem06** [comment]
tükçe dilde tema yüklenmedi sorunu hala düzelmedi .bu konu ile ilgili gelişme ne zaman olaki :(
