### ISSUE TITLE
Kamera dan Galeriye Geçiş

### ISSUE THREAD

**Issue by kocogluali** [ingbrzy/MA-XML-7.0-TURKISH#20]
Çekilen resime kameradan tıklayınca Galeri açılır gibi oluyor ve galeri kapanıyor. Orada bir buga giriyor

**Comment by raoc999** [comment]
Evet, bunun yanısıra 6.1.7 sürümünde oldukça fazla çevrilmemiş metin var. Gerekirse çevirilere yardımcı olabilirim. Redmi Note 2'den bende iki tane var. Referans olarakta oyun ve yazılım çevirilerim var.

**Comment by sedat27** [comment]
Kameradan resim onizleme sorunu bende de var. Redmi note3 sadece turkce de var. İngilizcede hersey normal. Lutfen sunu bi halledelim.tesekkurler

**Comment by sedat27** [comment]
Ayrica fotolar galeride fotograflarda gorunmuyor. Telefon- tum resimler bolumunde gorunuyor.
Gene sadece turkce de

**Comment by kocogluali** [comment]
dili ingilizce yapınca düzeliyor genel bir bug var malasef
