### ISSUE TITLE
Yeniden Çeviri -Redmi Note 2

### ISSUE THREAD

**Issue by raoc999** [ingbrzy/MA-XML-7.0-TURKISH#21]
Arkadaşlar, ürünleri Celaleddin diye bir arkadaşımız çeviriyor kendisine mail attım dönmedi fakat ben 6.1.14 sürümüne göre yeniden çeviri yapmaya başadım. Çünkü üründe pekçok yer güncellenmiş halen İngilizce ve bazı yerleri arkadaşımız gözden kaçırmış galiba yanlış çeviri olmuş. Araxis Merge ile arkadaşımız çevirisi ile güncel İngilizce sürümünü yeniden derliyorum. Bunu yaparken Redmi Note 2 ürününü esas alıyorum. Haftalık güncellemeleri takip ediyorum değişiklikleri hemen ekleyeceğim. Güncel sürümde 103 klasör var. %50sini bitirip hem buraya hemde Xiaomi'ye göndereceğim.

Buna neden ihtiyaç var:
1. Anlam kaymaları ve bazı yerlerden başka manalar çıkıyor
2. Etnik çeviriler hoş değil mesela "Ne Mutlu Türküm Diye" eklemiş arkadaş. Bende Türküm fakat çevirilerde bölge ve etnik sözler kullanılmaz. Çinli dese ki ne büyük biziz gerisi amele biz onun telefonunu almayız bile. Her kesimden insanın Türkçe kullanacağını göz önüne alarak yapmalıyız.
3. Artik Türkçe'mize giren bazı kelimeleri çevirmemek lazım Anti-Spam gibi.
vb...
Celaleddin arkadaş bazı yerleri yetiştirememiş olabilir ama bir gerçek var o da binlerce satırı programlamaya uygun çevirmiş gerçekten tebrik ediyorum eline sağlık. Ayrıca isterse onun öncülüğünde devam edebiliriz.
Orhan CAKMAK

**Comment by MIUITurkey** [comment]
Ne mutlu türküm yazan bolüm bu çevirinin en güzel yeridir.
20 Oca 2016 18:44 tarihinde "raoc999" <notifications@github.com> yazdı:

**Comment by raoc999** [comment]
Bu arada Türkçede gördüğüm hataların başında Kameradan çekilen fotoğraflara ulaşamama ve galerideki sorunlar var. Yeniden çevirirken İngilizce dosyalrı esas alacağımdan düzeleceğini tahmin ediyorum.

**Comment by raoc999** [comment]
MIUITurkey dediğin doğrudur ama Çinli böyle birşey görse ayrıca Cihan Türk olana kadar .... bazı yerler var kabul etmez. Markalar ırk, din istemez. memlekettimizde bizimle aynı dili konuşan çok hain var biliyorsun. Olaya Türkçe konuşan kişiler gözüyle bakmalıyız. Yoksa hainler, teröristeler diye ayırsak elde 10-15 milyon kişi kalır kalmaz

**Comment by MIUITurkey** [comment]
Çinli zaten Türkçeyi kullanmaz ayrıca orijinal çeviriyi zaten biz yaptık ve
o çeviride bunun yerine Hugo barra yazmakta.

Bir Amerikalı her filminde amerikan bayrağı kullanıyor ise bunun sebebi var
biliyorsunuz dimi. Politika.
Ben o şekilde kalmasından hatta daha fazla özlü söz yazılmasından yanayım.
Tabi çeviri sizin karar sizin.
20 Oca 2016 ÖS 6:50 tarihinde "raoc999" <notifications@github.com> yazdı:

**Comment by raoc999** [comment]
MIUITurkey ; Bazı konularda sana hak veriyorum. Bimiz kültürümüze ait ama herkesi ilgilendiren özlü sözler olabilir. Benim amacım Xiaominin de desteklediği bir proje olsun bir çıkar veya beklenti olmaksızın herkes severek kullansın ve Xiaomi Türkiyeye gelsin. Gerçi gelirse fiyatları şişecek ama en azından pahalı ürünlere rakip çıksın.

**Comment by MIUITurkey** [comment]
Hocam zaten Xiaomi firmasının Türkçe çevirisi mevcut. MIUI Türkiye ekibi
tarafından yapıldı. Çeviri %100 olarak tamamlandı. Ayrıca global romlarda
kullanılmaktadır.
20 Oca 2016 ÖS 7:17 tarihinde "raoc999" <notifications@github.com> yazdı:

**Comment by ekilciler** [comment]
Orhan hocam yeniden çeviriye başlamak gerçekten son derece zorlayıcı olacaktır. Benim tavsiyem Celaleddin hocamın cevap vermesini beklemeniz yönünde. Onun iznini ve fikrini aldıktan -ve tabii ki tecrübelerinden yararlandıktan- sonra yapmış olduğu çeviriyi yeniden düzenlemek işinizi çok daha fazla kolaylaştıracaktır zannediyorum.

İkinci olarak çeviride Bilişim Terimleri Sözlüğü'nün kullanılması hem daha profesyonel bir çeviri oluşmasına olanak sağlayacak hem de Türkçe'mizin temiz kalmasına yardım edecektir. Dolayısıyla bir terimin orijinal haliyle dilimize yerleşip yerleşmediğine karar verirken kişisel yargılarımız yerine genel kabul olmuş kuralların kullanılması çok daha uygundur. http://cayfer.bilkent.edu.tr/~cayfer/bilisim-sozlugu/tbd-ing-trk-sozluk.htm

Üçüncü olarak çevirilerde etnik özelliklerin kullanılması kullanıcıların firmaya olan bağlılıklarını artırması nedeniyle düşündüğünüzden çok daha kabul edilebilir düzeydedir. Bu nedenle "bizleri" yansıtan ögeleri değiştirmemeniz çok daha olumlu sonuçlar doğuracaktır.

Ve son olarak global romlarda tamamı hatasız bir şekilde çevrilmiş olan ve sürekli güncel bir çevirimiz zaten var. Kişisel olarak veya MIUI Türkiye ekibi olarak orayı kullanmanızın bizce her hangi bir sakıncası yok ancak bu çeviri resmi olarak Xiaomi'nin ve özellikle bu dönemde bu çeviriyi kullanmanıza izin vereceklerini hiç zannetmiyorum.

Kolay gelsin.

**Comment by raoc999** [comment]
Tavsiyeleriniz için teşekkürler, Celaleddin kardeşimizde dönüş yaptı, dediklerinize katılıyorum ve hazır yapılmış çevirinizi baz alarak gidiyorum. Benim yaptığım aslında Haftalık ROM'u takip etmek. Birde birden fazla telefonda klasik hale gelen tabirlere dönmek. Birde menüde herşey "Uçak Modu, VPN, İnternet Paylaşımı, Mobil planı"  simetri olsun istiyorum. Yani "Mobil Planı" gibi. Yahu neye bakıyorsun diyebilirsiniz. Ama olsa hoş olur. Çok güzel bir çalışma yapmışsınız ben sadece sizin %10 eksiğinizi tamamlamaya çalışacağım. Birde haftalık güncellemelerde bazı yerleri ekleyip bazı yerleri çıkartıyorlar. Şevkimi kırmayın :) Tavsiyelerinizi dikkate alıyorum, teşekkürler

**Comment by raoc999** [comment]
Çeviriyi 6.1.21 sürümüyle devam ediyorum. Son olarak Browser.apk dosyasını çevirdim. Var olan Türkçe sürümdeki pek çok satır kaldırılmış ve yerine daha fazla satır eklenmiş.Var olan çeviride "Deny" gibi kelimeler "Engelle" diye çevrilmiş. Maalesef Türkçe kuşa dönmüş. Bazı kelimelerin karşılığını yazarken kırk defa düşünmek gerekiyor. Bazı yerleri çok güzel düşünerek çevirmiş arkadaşlar, bazı yerleri tamamen farklı manada çevirmişler.

**Comment by MIUITurkey** [comment]
github linkini atarmısın çevirinin uzun zaman oldu oraya bakmayalım.

22 Ocak 2016 18:17 tarihinde raoc999 <notifications@github.com> yazdı:

> Çeviriyi 6.1.21 sürümüyle devam ediyorum. Son olarak Browser.apk dosyasını
> çevirdim. Var olan Türkçe sürümdeki pek çok satır kaldırılmış ve yerine
> daha fazla satır eklenmiş.Var olan çeviride "Deny" gibi kelimeler "Engelle"
> diye çevrilmiş. Maalesef Türkçe kuşa dönmüş. Bazı kelimelerin karşılığını
> yazarken kırk defa düşünmek gerekiyor. Bazı yerleri çok güzel düşünerek
> çevirmiş arkadaşlar, bazı yerleri tamamen farklı manada çevirmişler.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ingbrzy/MA-XML-7.0-TURKISH/issues/21#issuecomment-173965955>
> .
>



-- 
[image: MIUI Türkiye Forumu]

**Comment by MIUITurkey** [comment]
Tamam buldum zaten hemen.

22 Ocak 2016 18:19 tarihinde Hasan ÖZKAN <hasan.ozkan.35@gmail.com> yazdı:

> github linkini atarmısın çevirinin uzun zaman oldu oraya bakmayalım.
>
> 22 Ocak 2016 18:17 tarihinde raoc999 <notifications@github.com> yazdı:
>
>> Çeviriyi 6.1.21 sürümüyle devam ediyorum. Son olarak Browser.apk
>> dosyasını çevirdim. Var olan Türkçe sürümdeki pek çok satır kaldırılmış ve
>> yerine daha fazla satır eklenmiş.Var olan çeviride "Deny" gibi kelimeler
>> "Engelle" diye çevrilmiş. Maalesef Türkçe kuşa dönmüş. Bazı kelimelerin
>> karşılığını yazarken kırk defa düşünmek gerekiyor. Bazı yerleri çok güzel
>> düşünerek çevirmiş arkadaşlar, bazı yerleri tamamen farklı manada
>> çevirmişler.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ingbrzy/MA-XML-7.0-TURKISH/issues/21#issuecomment-173965955>
>> .
>>
>
>
>
> --
> [image: MIUI Türkiye Forumu]
>



-- 
[image: MIUI Türkiye Forumu]

**Comment by raoc999** [comment]
github linkinde benim birşeyim yok çünkü Araxis Merge ile güncel İngilizce ile var olan Türkçe çeviriyi karşılaştırarak Orj. İngilizce üzerinde çeviri yapıyorum. Çeviri yapan arkaaşların çevirisini gözeterek. Şimdi github yazılımını indiriyorum, oradan da eklerim.
