### ISSUE TITLE
Redmi note 3 kamera ve galeri sorunu

### ISSUE THREAD

**Issue by sedat27** [ingbrzy/MA-XML-7.0-TURKISH#22]
Kamerada önizleme de ve galeride fotograflari goruntulemede sorun var. Sanirim cok eskiden beri var. Oralar ingilizce kalsada olur simdilik kullanamamaktansa daha iyidir. En azindan gerisini Turkce kullanabiliriz. Saygilar

**Comment by raoc999** [comment]
Çeviri yaparken kaynaklanan bir hata veya çeviriden sonra gelen mini bir değişikliğin çeviriye yansımamasından kaynaklanıyor olabilir. Örneğin en güncel 6.1.14 sürümde bir satır "&lt;font color=#DF0000&gt;Reddet&lt;/font&gt;" şekilde iken Türkçe karşılığı "Engelle" olarak duruyor. Dediğim gibi belki önceden sadece "Engelle" idi sonra daha farklı hale geldi. Daha farlı birşey de olabilir. Örneğe takılmayın...

**Comment by sedat27** [comment]
Bu sorun ceviriden kaynaklaniyorsa cozulur herhalde. Sizce yakin zamanda hallolacak bir sorun mu? Yoksa daha cok beklemekmi gerekecek? Baska romlara gecelim mi? Ancak ben hep buradan rom kullandim. Baska hicbir sorun yok.bu halledilirse efsane olur!!!

**Comment by raoc999** [comment]
Ben bitirdiklerimi arkadaşlara (TR Çeviriyi yapan) mail olarak atacağım en azından 18 dizinin çevirisini bitirdim ve bir sonraki 6.1.XX gelecekse onlarda düzgün gözükürler. Alfabetik olarak gidiyorum. Kamera gelecek haftaya biter gibi. Benide en çok kamera ve galeri sıkıyor. Ayrıca 6.1.21 sürümünde şu ana kadar bür sürü yenilikler eklenmiş İng. sürümde görüyorum TRde yok. bu sorunda umarım gidecek. -Redmi Note 2 için-

**Comment by sedat27** [comment]
yani netice de düzelecemidir?

**Comment by raoc999** [comment]
Eğer çeviri dosyasından kaynaklanıyorsa düzelecek ki dili İng. yapınca sorun olmadığına göre çeviri dosyalarından kaynaklanıyor, adamlar pekçok yeri kaldırıp yeni şeyler eklemişler. Mesela bir dosya 10kb ise güncel soürüm 15kb olmuş nedeyse 100-200 satır ekledikleri dosya var. Bitmiş 16 dosyayı çeviride yetkili olan arkadaşa attım...

**Comment by sedat27** [comment]
valla düzelirse. efsane olursun:)
dosya boyutları arttığına göre ek özellikler eklemişler midir?
öyleyse gayet güzel olur.
yardımların teşekkürler

**Comment by raoc999** [comment]
Kamera dosyasını güncelledim, gelen hataları da gün içinde düzeltirim. Bakalım sonraki güncellemede gidecek mi. Güncel 6.1.29 sürümüne göre var olan çeviri 81 satır fazla idi.

**Comment by sedat27** [comment]
Umarim duzelmistir. Haftaya anlariz artik.

**Comment by immortalcain** [comment]
gerçekten en can sıkıcı problem, umarım biran önce düzelir.

**Comment by raoc999** [comment]
Arkadaşlar Galeri ve Kamera çevirilerini bitirdim ve yayınladım Sadece Galeride çok uzun birkaç satır vardı başları Data/ ile başlayıp \Data ile bitiyordu o satırlarda \Veri diye çevirdim buralar hatalı olabilir. Diğer dillere baktım o satırlar yok. Ya onlarda eski ya da sildiler. Hata raporu gelsin düzeltirim. Umarim bu kez Galeri ve Kamera düzelir. Düzelmezse halen çeviride birşey var, diğer dosyaları çevirmeye devam. Gerekirse Almanca ile Galeri ve Kamera dosyalarını karşılaştıracağım.

**Comment by sedat27** [comment]
Sorun devam ediyor

**Comment by sedat27** [comment]
@raoc999 malesef 6.2.25 kamera sorunu devam ediyor.

ayrıca "kilit ekranı ve parmakizi okuyucu" menu başlığı "PArmakizi" olarak yazılmış.

**Comment by immortalcain** [comment]
Telefonum redmi note 3 6.9.22 versiyonundayım son birkaç versiyonda bu hata yeniden başladı şu an galeriye gitmiyor kameradan
