### ISSUE TITLE
6.3.24 Sonraki TR Çeviri Hakkında !

### ISSUE THREAD

**Issue by raoc999** [ingbrzy/MA-XML-7.0-TURKISH#33]
Arkadaşlar benim yaptığım çeviriyi MIUI Türkiye takimi tamamen silip kendi çevirilerini eklemişler. Kendilerine başarılar diliyorum. Ama bir kaç dosyalarını inceledim. Özellikle "Sd kart, Wps, İms, Mms" gibi kısaltmaları çok düzensiz ve küçük harfle yazmışlar. Bunların kesinlikle düzeltilmesi lazım. Sadece Ayarlar dosyasında program 1000 kadar yazım imla hatası buluyor. Bunlarda %90 NFC yerine Nfc, HCI yerine Hci gibi... Benim çevirim harikaydı demiyorum, buradaki arkadaşlar sayesinde hergün iyiye gidiyordu. Bence elden geçirmeniz lazım. Ben çeviriye bu tür hatalar için başlamıştım yolun sonunda aynı yere geldik. Sorun yok ben kendi çevirimi kullanmaya devam edeceğim. Sizin çeviri tam randımanlı hale geçince sizin çeviriye geçiş yapacağım. Çalışmanızda başarılar diliyorum. Aslında şöyle yapsaydınız daha iyi olurdu: Benim çeviri dosyalarını alıp, arkadaşlarında söylediği hataları düzeltip, üzerinden devam etseydiniz çok iyi olurdu. Çünkü ben Celalleddinin dosyalarını derlemiştim.

**Comment by MIUITurkey** [comment]
Hocam çeviri hepimizin ortak çalışması olacak zaten eksik bölümleri
düzenlerseniz zaten onaylanacaktır herkesin yardımı ile daha iyi hale
gelecektir aslında crowdin çevirisini direk buraya yüklemek isterdim ama
iki site arasında bazı farklılıklar var bu da kod sorunu olacak yoksa resmi
çeviri zaten bizim tarafımızda yapıldı
31 Mar 2016 10:17 tarihinde "recep.ali.orhan.cakmak" <
notifications@github.com> yazdı:

**Comment by raoc999** [comment]
Hasan dediğim gibi kısaltmalar evrensel artık Sd kart yok SD Kart. Bu hafta yayınlayın bakalım nasıl olacak, etki-tepki. Eğer beğenilirse sorun yok zaten. Sadece imlâ hataları vardır. Onlarda düzeltilir. Ama keşke bana söyleseydin de dosyaları Araxis Merge eşitleseydim. Böylece sizdeki ekstra satır ve çevirileri eklemiş olurduk. Şimdilik yarını görelim. En azından Redmi Note 2 hariç cihazlar içinde çeviri var....

**Comment by MIUITurkey** [comment]
Hocam onu tekrar hakan ile konuşup ortak çalışma yapılabilir zaten çeviri
sizde mevcut diye düşünüyorum sanırım arkadaşlar bu haftaya yetişsin diye
biraz hızlı davrandı

Siz hakan ile bir konuşun bence ortak çalışma ile mükemmel bir iş
çıkacaktır ortaya
31 Mar 2016 10:26 tarihinde "recep.ali.orhan.cakmak" <
notifications@github.com> yazdı:

**Comment by raoc999** [comment]
Hakan? Yarın derleme yapılsın görelim. Ona göre konuşuruz. İnş. gerek kalmaz.

**Comment by MIUITurkey** [comment]
Şuan çeviri işi komple onda tanıştırırım sizi
31 Mar 2016 10:30 tarihinde "recep.ali.orhan.cakmak" <
notifications@github.com> yazdı:

**Comment by raoc999** [comment]
Hasan bence Hakan'a söyle istersen, şu an sadece Ayarlar dosyasının çevirisini inceliyorum.Kesme işaretleri yok, Büyük harfle yazılması gereken kısaltmalar hep küçük harfle, itme abonelikleri, Arka plan gibi bitişik yazılması gereken yerler......

**Comment by MIUITurkey** [comment]
Tamamdır
31 Mar 2016 10:37 tarihinde "recep.ali.orhan.cakmak" <
notifications@github.com> yazdı:
