### ISSUE TITLE
Çevirimci Ekibin Dikkatine!!!

### ISSUE THREAD

**Issue by raoc999** [ingbrzy/MA-XML-7.0-TURKISH#40]
Arkadaşlar haberim olmadan değişiklik yapmayın, lütfen bana bildirim, ben başka bir yazılımla zincirleme yapıyorum. Değişiklikleri, hataları vb bana söyleyin lütfen!. Ayrıca upload etmeyin ki ben sürümleri görebileyim. -Hasan sözüm sana ;))

**Comment by MIUITurkey** [comment]
değişilik tek harfte yaptım :)

11.04.2016 tarihinde recep.ali.orhan.cakmak <notifications@github.com> yazmış:
> Arkadaşlar haberim olmadan değişiklik yapmayın, lütfen bana bildirim, ben
> başka bir yazılımla zincirleme yapıyorum. Değişiklikleri, hataları vb bana
> söyleyin lütfen!. Ayrıca upload etmeyin ki ben sürümleri görebileyim. -Hasan
> sözüm sana ;))
>
> ---
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/ingbrzy/MA-XML-7.0-TURKISH/issues/40


-- 
[image: MIUI Türkiye Forumu]
