### ISSUE TITLE
Çevrilmesi Gereken Dosyalar !!!

### ISSUE THREAD

**Issue by raoc999** [ingbrzy/MA-XML-7.0-TURKISH#41]
Arkadaşlar, (Hasan-Hakan) veya gönüllüler: Şu dosyaları kendi aranızda paylaşarak çevirip mail adresime gönderirseniz çok sevinirim. Gönüllü arkadaşlar MUIU Türkiye sitesinden vb... Hasan arkadaşımızla bağlantıya geçsinler. ÇEviriler yapıldıktan sonra direk bana veya Hasan arkadaşımız aracılığıyla yine bana atsınlar. Ben düzenleyip yükleme yapayım.

Çevrilmesi gereken dosyalar:
1: mediatek-res.apk
2: MiBand.apk
3: MiKey.apk
4: MiTagApp.apk
5: MiuiSuperMarket.apk

Diğerlerini sonra yazacağım yeni FW Güncelleme dosyası bir sonraki düzenleme olduğundan onu ben çeviririm... Mail adresim: raocakmak@gmail.com

**Comment by MIUITurkey** [comment]
Bunların hakan da olması gerek o atacaktır hocam olmadı forum ekibi ile
halledilir.
12 Nis 2016 ÖS 7:47 tarihinde "recep.ali.orhan.cakmak" <
notifications@github.com> yazdı:

**Comment by raoc999** [comment]
mediatek-res dosyasını çevirip ekledim. Galiba bu mediatek işlemcili telefonlarla alakalı. Benim telefonunda tüm çevirisin yapmama rağmen gelen ingilizce mesajlar vardı. Bu mesajlar bu dosyanın içinde vardı... Hayırlı olsun. Güncelleme gelmeden son gol olsun :)

**Comment by raoc999** [comment]
MuiVideoPlayer adlı yeni dosyada uzatma golu olarak çevrilip, eklendi.
