### ISSUE TITLE
3g 4g

### ISSUE THREAD

**Issue by sener05** [ingbrzy/MA-XML-7.0-TURKISH#45]
Merhabalar.  Redmi note 2 kullanıyorum yeni surumu yukledim ve 3g. 4g geçiş seçeneği komple silinmis yani geçiş yapmak için mobil bağlantı seçenek bölümü yok.. Teşekkürler.

**Comment by raoc999** [comment]
Cevap yazmıştım ama yeniden yazalım, 6.3.24 alt sürüme ait ayarlar vb... indirdim. Gelecek hafta 6.4.14 sürümüne ait derlemeleri yapıp yükleme yapacağım. Fazlasıyla gelecek... :)

**Comment by raoc999** [comment]
Sener05 : SIM Kartın içinde "Tercih Edilen Ağ Tipi"nden mi bahsediyorsun. Bende de Redmi Note 2 var ve 3G-4G-2G seçimi yapabiliyorum? Bir bak istersen. Başka yerden bahsediyorsan ayrı...
