### ISSUE TITLE
Redmi Note 2 - Kamera Önizleme Hatası

### ISSUE THREAD

**Issue by seyitacar** [ingbrzy/MA-XML-7.0-TURKISH#9]
Xiaomi Redmi Note 2 MIUI V7'de fotoğraf çektikten sonra önizleme resmine tıklayınca göstermiyor, dili İngilizce olarak değiştirince sorun yok

**Comment by cmadencan** [comment]
Selam bu hafta ilgili güncellemeler yapıldı. Bir şey sormak istiyorum MI4
imei atabiliyor musun?

30 Eylül 2015 00:04 tarihinde seyitacar23 <notifications@github.com> yazdı:

**Comment by seyitacar23** [comment]
Ben atmıyorum ama atılabiliyor hatta sana anlatim linkini vereyim kendin
bile yapabilirsin

http://akilli.be/forum/konu-snapdragon-cihazlarin-imei-tamiri-nasil-yapilir

Bu arada ilgin icin tesekkur ederim, kullanicilarin bildirdigi bir sorun
daha var Miui v6 de sorunsuz olarak calisan Vakıfbank uygulaması Miui V7 de
bir türlü aktif olmuyormuş, rica etsem bakabilir misin?

1 Ekim 2015 10:11 tarihinde Celaleddin <notifications@github.com> yazdı:

**Comment by MIUITurkey** [comment]
Sorun olursa gönder bana atarız
1 Eki 2015 12:41 tarihinde "seyitacar23" <notifications@github.com> yazdı:

**Comment by cmadencan** [comment]
Aslına bakarsan v6 ve v7 sürümü sadece numara yükseltmek için yapılan bir
sürüm oldu ve bir türlü sorunlardan arındırılamadı, kullanıcılar ve
yöneticiler bunun farkında ve bu nedenle hala stabil v5 sürüm yayınlanıyor.
vakıfbank uygulamasındaki sorun tam olaak nedir??
Bu arada imei ile uğraşacak vaktim yok o nedenle sordum, sanırım
donanimhaberde bir yazını görmüştüm.

1 Ekim 2015 12:45 tarihinde Hasan <notifications@github.com> yazdı:

**Comment by seyitacar23** [comment]
Donanımhaberde yazımı görmüş olabilirsin (eğer aynı konudan bahsediyorsak cahillik dönemimde açılmış bir konuydu) ama eğer İstanbul'da veya İzmir'de isen yardımcı olurum.

Ayrıca Vakıfbanktaki sorunu yaşayan kullanıcılardan birinin yorumunu aynen yazıyorum umarım çözüm bulabilirsin.

Seyit hocam şimdi program aktivasyon istiyor...
tıklıyorum müşteri numaramı ve internet şifremi giriyorum...
sonra mobil imza ile gir var bide aktivasyon kodu ile gir var...
mobil imza ile giriyorum...
hanımın telefonunda da aynı program olduğu için onay istiyor hanımın telinden onay veriyorum...
sonra telefon için 6 haneli şifre oluşturuyosun...
ondan sonra uygulamaya girmem lazım fakat tekrar aktivasyon (en başa alıyor) menüsüne alıyor...
sorun bu şekil...
mıuı 6 ve aosp romda denendi sıkıntı yok...

**Comment by cmadencan** [comment]
araçlardan uygulamaya otomatik başlatma izni verip
uygulama ayarları-vakıfbank uygulaması- yetki yönetiminden tüm izinlere
çentik koyup tekrar denesin..

1 Ekim 2015 20:23 tarihinde seyitacar23 <notifications@github.com> yazdı:

**Comment by seyitacar23** [comment]
Kamera önizleme hatası halen düzelmiş değil ayrıca Vakıfbank uygulaması problemi de devam ediyor

**Comment by sedat27** [comment]
Türkçe dilde uzun zamandır temalarda liste yüklenemedi veya bağlantı yok hatası alınıyor.Hiçte düzelmiyor. Bilinmiyormu bu hata yoksa düzelemiyormu?
Mi4 Cancro

**Comment by nonstradam** [comment]
kamera önizleme sorunu devam ediyor. lütfen yardımcı olurmusunuz.

**Comment by yasinkilinc** [comment]
Merhaba,
@cmadencan  sadece rom'daki dil problemlerini mi çözüyorsunuz? yoksa programatik hatalarıda çözüyor musunuz? @nonstradam kamera önizleme problemini sorduğu için sordum.

Eğer rom'daki programatik hataları çözüm için bir yönerge filan varsa linkini gönderebilir misiniz?

Teşekkür ederim....

**Comment by gaskiney** [comment]
@cmadencan vakıfbank uygulaması sorunu hala düzelmedi dediğiniz gibi yaptım yine olmadı.  Tek umudumuz siz kaldınız

**Comment by haszen** [comment]
Kamera önizleme sorunu sadece türkçe dilinde var diğer tüm diller de böyle bi sorun yok türkçe çeviri yapılırken çevrilmemesi gereken yerler türkçeye çevrildiğinden olabilir

**Comment by haszen** [comment]
Su an redmi note 2 kullanıyorum 7.2.3.0 global rom yüklü Türkçe dilde kamera onizleme sorunu hala var nasıl çözülmüş
